### ISSUE TITLE
SQL to DDlog compiler misses table name in context for windowed queries over JOINed tables

### ISSUE THREAD

**Issue by amytai** [vmware/differential-datalog#1083]
Query:
```
SELECT DISTINCT t1.column2, AVG(t2.column1) OVER (PARTITION by t1.column3) AS avg
         FROM t1
         JOIN t2
             ON t1.column1 = t2.column1
```

Error:
```
com.vmware.ddlog.translator.TranslationException: Could not resolve identifier
t1 line: 2 column: 17

	at com.vmware.ddlog.translator.ExpressionTranslationVisitor.visitIdentifier(ExpressionTranslationVisitor.java:349)
	at com.vmware.ddlog.translator.ExpressionTranslationVisitor.visitIdentifier(ExpressionTranslationVisitor.java:39)
	at com.facebook.presto.sql.tree.Identifier.accept(Identifier.java:70)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
...
```

**Comment by ryzhyk** [comment]
@amytai , ok to close this issue?
