### ISSUE TITLE
Regression in souffle tests

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#332]
Looks like there is a new souffle test we're failing:

```
Testing example/floydwarshall
Traceback (most recent call last):
  File "./run-souffle-tests.py", line 322, in <module>
    main()
  File "./run-souffle-tests.py", line 285, in main
    modules = run_remote_tests()
  File "./run-souffle-tests.py", line 209, in run_remote_tests
    code = compile_example(directory, test + ".dl")
  File "./run-souffle-tests.py", line 120, in compile_example
    convert(f + ".tmp", "souffle", options)
  File "/home/lryzhyk/projects/differential-datalog/test/../tools/souffle_converter.py", line 1372, in convert
    tree = parser.parse_file(files.inputName)
  File "/usr/local/lib/python2.7/dist-packages/parglare/parser.py", line 132, in parse_file
    return self.parse(content, file_name=file_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/parglare/parser.py", line 203, in parse
    raise error
parglare.exceptions.ParseError: Error at floydwarshall.dl.tmp:68:18:"w.NumNodes*, fw.Edge\n" => Expected: ( or COMP or DECL or DOT or EOF or FUNCTOR or INIT or INPUT or INSTANTIATE or Identifier or NUMBER_TYPE or OUTPUT or OVERRIDE or PRAGMA or PRINTSIZE or SYMBOL_TYPE or TYPE or } but found <,(,)> or <NotComment(,)>
```

**Comment by mbudiu-vmw** [comment]
Could be a recursive data type.

**Comment by mbudiu-vmw** [comment]
Looking into this.
