### ISSUE TITLE
SQL-ddlog compiler: support "primary key" in create table DDL

### ISSUE THREAD

**Issue by lalithsuresh** [vmware/differential-datalog#807]
The following SQL `create table hosts (id varchar(36) primary key, capacity integer, up boolean)` currently triggers a parsing exception with Presto.

```

	at com.facebook.presto.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:3616)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:252)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:173)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:108)
	at com.vmware.ddlog.translator.Translator.translateSqlStatement(Translator.java:62)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at ddlog.JooqProviderTest.compileAndLoad(JooqProviderTest.java:97)
	at ddlog.JooqProviderTest.testInsertAndSelect(JooqProviderTest.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:270)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:2083)
	... 32 more


Process finished with exit code 255
```

**Comment by mbudiu-vmw** [comment]
If presto cannot parse it there is not much we can do about it. Maybe you can upgrade to a newer version of Presto.

**Comment by lalithsuresh** [comment]
Hurray for non-standard SQL dialects!

`create table hosts (id varchar(36) with (primary_key = true), capacity integer, up boolean)` is the way to do it in Presto. This appears in the SQL AST as a property for Columns. I think it's `ColumnDefinition.getProperties()`.

I'd need to watch out for it when passing these create statements to JOOQ/H2 in my JooqProvider, because JOOQ does not yet support Presto. I'd need to re-write `with (primary_key = true)` into just `primary key`.

**Comment by mbudiu-vmw** [comment]
So you have to do this for each column that is part of the primary key?

**Comment by lalithsuresh** [comment]
Yes, that seems to be the case.
