### ISSUE TITLE
Tests failing on OSX

### ISSUE THREAD

**Issue by lalithsuresh** [vmware/differential-datalog#897]
There's been a regression sometime over the last few weeks. I can no longer run the `JooqProviderTest`. The compilation API (`DDlogAPI.compileDDlogProgram()`) fails with the following error:

```
 Compiling types v0.1.0 (/private/tmp/program_ddlog/types)
    Finished release [optimized] target(s) in 2m 42s
Running cc -shared -fPIC -I/Users/lsuresh/.jenv/versions/openjdk64-12.0.1/include -I/Users/lsuresh/.jenv/versions/openjdk64-12.0.1/include/darwin -I/tmp/program_ddlog -I/Users/lsuresh/code/ddlog-git/lib /Users/lsuresh/code/ddlog-git/java/ddlogapi.c -L/tmp/program_ddlog/target/release/ -lprogram_ddlog -o libddlogapi.dylib
Undefined symbols for architecture x86_64:
  "_ddlog_log_set_callback", referenced from:
      _Java_ddlogapi_DDlogAPI_ddlog_1log_1replace_1callback in ddlogapi-285729.o
  "_ddlog_log_set_default_callback", referenced from:
      _Java_ddlogapi_DDlogAPI_ddlog_1log_1replace_1default_1callback in ddlogapi-285729.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error running cc -shared -fPIC -I/Users/lsuresh/.jenv/versions/openjdk64-12.0.1/include -I/Users/lsuresh/.jenv/versions/openjdk64-12.0.1/include/darwin -I/tmp/program_ddlog -I/Users/lsuresh/code/ddlog-git/lib /Users/lsuresh/code/ddlog-git/java/ddlogapi.c -L/tmp/program_ddlog/target/release/ -lprogram_ddlog -o libddlogapi.dylib

Test ignored.

Test ignored.

Test ignored.

Test ignored.

Test ignored.

Test ignored.

Test ignored.

java.lang.RuntimeException: Failed to compile ddlog program

	at ddlog.JooqProviderTest.compileAndLoad(JooqProviderTest.java:253)
	at ddlog.JooqProviderTest.setup(JooqProviderTest.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

I first noticed this on some private branches a week ago when I rebased to use the newer DDlog compilation API. This fails on current master (72842397a75d73c88c57c2e0882d35abd05997e4) as well.

**Comment by mbudiu-vmw** [comment]
This can be reproduced with `./test.sh sql`

**Comment by mbudiu-vmw** [comment]
Indeed, `./test.sh java0` works, while `./test.sh java1` does not.
(The java0 by default does a debug build, but even with release it still works.)

So far I have discovered that the missing symbols are not in the .a file produced by the rust compiler in target/release. Still investigating.

**Comment by mbudiu-vmw** [comment]
It's a problem with the dependency management in DDlog. If you add the following to resist.dl: `import log` then the test `java1` passes. Note that the missing symbols `_ddlog_log_set_default_callback` have recently been moved from the standard library to the log library.

**Comment by lalithsuresh** [comment]
Why does it only affect OSX though?

**Comment by mbudiu-vmw** [comment]
Until we find out you can work around this by importing log yourself

**Comment by lalithsuresh** [comment]
Will need to add it to the Sql -> ddlog compiler then

**Comment by ryzhyk** [comment]
@lalithsuresh , can you try this out: #899 

thanks!

**Comment by lalithsuresh** [comment]
@ryzhyk #899 works for me.
